### ISSUE TITLE
Latest WPorg release (0.10.0) was built & released with the .git directory

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/zoninator#108]
Commit: https://plugins.trac.wordpress.org/changeset/3134172/

This is giving errors in site repositories when being built through TeamCity, because of:

> Error: The repository has a git submodule but has no .gitmodules configuration in the root directory.

CC @GaryJones

**Comment by rebeccahum** [comment]
@GaryJones @GaryJones @GaryJones who doesn't know how to relax

**Comment by GaryJones** [comment]
Patched in `develop` via https://github.com/Automattic/zoninator/commit/6f705c856db915a42facdf1f8217445fbd5fc422 a few days ago, but isn't in the 0.10.0 release. 

I'll cherry-pick this for a hotfix as a 0.10.1 release.

**Comment by GaryJones** [comment]
Closed in #109. See #106.
