### ISSUE TITLE
get_supported_post_types() shouldn't fire on init

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/zoninator#2]
Because it does, `$this->post_types` becomes set without potentially additional post types that just happen to be registered after.

It doesn't look like that class variable is ever used, so it would probably be better to remove it altogether.

Also, the taxonomy should be registered with post types on late init to ensure all post types have been registered.

**Comment by brettshumaker** [comment]
@sboisvert
I believe this was mostly addressed by a0beb6d which added a priority of `99` to the `init` hook that calls `Zoninator->init()`.

> It doesn't look like that class variable is ever used

Correct, I don't see a need to keep it around unless we're interested in keeping backwards compatibility for anyone who has code relying on that class variable being there.

Thoughts?

**Comment by sboisvert** [comment]
>unless we're interested in keeping backwards compatibility for anyone who has code relying on that class variable being there.

I guess folks could be using it.... If we don't need to change it let's not :)
