### ISSUE TITLE
WordPress 4.2 Term Splitting

### ISSUE THREAD

**Issue by mboynes** [Automattic/zoninator#27]
Zoninator needs to be patched to deal with [potential term splitting issues as of 4.2](https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/).

The main issue is that posts are related to zones via meta key, and that meta key is a reference to the zone's term ID. If a zone were to be updated (not its posts, but the zone itself), and that zone were a shared term, it would be split and the post relationships would be broken.

**Comment by bcampeau** [comment]
Can you submit a patch?

**Comment by mboynes** [comment]
I don't think I'll have time (working on patching lots of other code).

Can anyone at Automattic jump on this?

**Comment by mjangda** [comment]
Fixed in #28
