### ISSUE TITLE
Create zones for PHPUnit testing. 

### ISSUE THREAD

**Issue by jitendraharpalani58** [Automattic/zoninator#32]
Hi,

Is it possible to create a test zone for unit testing? 

I have a situation where my right rail template will load only if there is a zone that populates the videos in that right rail. Now, my unit test fails because the right rail is never generated in my test post. 

I looked up your code. All the setter methods are private, which makes it really hard to create any test data. 

Any thoughts ? 

Thanks

**Comment by mjangda** [comment]
Maybe something like this?

```
global $zoninator;
$zoninator->insert_zone( 'right-rail', 'Right Rail Videos', array( 'description' => 'Videos shown in the right rail' ) );
```

**Comment by jitendraharpalani58** [comment]
@mjangda Thanks ! 

I was able to create a zone using global variable. I had to use `add_zone_posts` method to add some videos.
