### ISSUE TITLE
Duplicate WP_Queries in get_zone_posts

### ISSUE THREAD

**Issue by jessedyck** [Automattic/zoninator#35]
I'm trying to perform some actions on each query being executed on a page, using the pre_get_posts action. I'm finding that zoninator loops are executing the query twice for each loop when I use z_get_posts_in_zone to get a list of arrays. 

The first one is in [zoninator.php on line 1012](https://github.com/Automattic/zoninator/blob/master/zoninator.php#L1012). get_zone_posts() runs get_zone_query() which returns a new WP_Query back to get_zone_posts. https://github.com/Automattic/zoninator/blob/master/zoninator.php#L1056

The second is when get_posts is called on that query on line 1013 [here](https://github.com/Automattic/zoninator/blob/master/zoninator.php#L1013). get_posts() also also creates a new WP_Query as you can see [here](https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-includes/post.php#L1876).

I couldn't find anything to support this being the desired effect, and I can't think of a scenario in this case where running 2 queries would be needed.

**Comment by mjangda** [comment]
Yeah, that's a bit silly :) Want to send over a PR to fix that? We can just
access the `posts` property for `WP_Query` instead of the `get_posts()`
call.

**Comment by jessedyck** [comment]
Not a problem! PR sent - https://github.com/Automattic/zoninator/pull/36
