### ISSUE TITLE
WordPress 4.4 broke the nav

### ISSUE THREAD

**Issue by bcampeau** [Automattic/zoninator#38]
WordPress 4.4 broke the CSS for the left nav. It reverted to the old tab design in a jumbled list. Will be working on a fix for this later today.

**Comment by mjangda** [comment]
Nice, thanks for working on this.

**Comment by bcampeau** [comment]
@mjangda ready for you to take a look. You may want to ?w=1 this since there was a lot of excess whitespace I trimmed on editing.

Thanks.

**Comment by bcampeau** [comment]
The fix is merged. Do you want to handle getting this pushed to VIP and .org? I can ping VIP if you'd prefer.

Thanks.

**Comment by joshbetz** [comment]
@bcampeau Merged on VIP :)
