### ISSUE TITLE
Drag and Drop on Mobile Issue

### ISSUE THREAD

**Issue by gracejiyoung** [Automattic/zoninator#41]
It looks like the drag-and-drop is not working on mobile devices. If you touch one of the stories in the zones to change the rank, it will scroll all the way to the bottom making it impossible to move the stories up or around. This was reproduced on iPhone6/iPhone6+ in Safari/Chrome. However, this does work properly on iPad.

**Comment by mjangda** [comment]
I think we need to patch in mobile support for jQuery UI or switch to a different drag-and-drop library.

**Comment by bcampeau** [comment]
@gracejiyoung what version of WordPress was this on? I'm assuming 4.4? I feel like this was working before so it *could* be caused by the latest version as some styles definitely broke (which I fixed) when I upgraded.

**Comment by sboisvert** [comment]
@brettshumaker Can you take a look?

**Comment by brettshumaker** [comment]
@sboisvert I believe I've fixed this here: bfe91dfcb35f653cf63da863784790ee2a8506b5

Found a closed issue on the touch punch github (https://github.com/furf/jquery-ui-touch-punch/issues/288) that referenced a similar issue.

**Comment by GaryJones** [comment]
No further feedback, so considered addressed.
