### ISSUE TITLE
Versioning in Wpackagist

### ISSUE THREAD

**Issue by yavormilchev** [Automattic/zoninator#65]
Hello,

We noticed that the versioning of your plugin is off at `https://wpackagist.org/search?q=zoninator`

It's not picking up the `0.7` release and it is still pulling the `0.6` version with the deprecated constructor name in `Zoninator_ZonePosts_Widget`.

Is there any way you can push the release to `https://wpackagist.org`? Do you have any plans to add the plugin to `https://packagist.org/`?

Thank you in advance!

**Comment by sboisvert** [comment]
@brettshumaker What are your thoughts?

**Comment by brettshumaker** [comment]
@sboisvert It looks like specifying `"wpackagist-plugin/zoninator":"0.7"` in `composer.json` _does_ pull version `0.7` which, as noted in #67, has the incorrect version number of `0.6` in `zoninator.php`.

Seeing as how the plugin is now at version `0.8`, and wpackagist is serving the correct version when specified, I think we can close this.

**Comment by sboisvert** [comment]
@yavormilchev let us know if this doesn't work for you.

Thanks!

**Comment by yavormilchev** [comment]
Got it thank you for the help!
