### ISSUE TITLE
Change the Version Number in Tag 0.7

### ISSUE THREAD

**Issue by achaitanyajami** [Automattic/zoninator#67]
We have a latest update form Vip to update Zoninator plugin to 0.7.
 
But we found out that, the version number in https://github.com/Automattic/zoninator/tree/0.7 was not changed.

Can you please change the version number, it's confusing.

**Comment by david-binda** [comment]
Thanks for flagging that @achaitanyajami  !

Related: Zoninator in plugin's directory is currently already on v0.8. We really should sync the versions across the board.

**Comment by sboisvert** [comment]
@brettshumaker Do you think this can be closed?

**Comment by brettshumaker** [comment]
@sboisvert Yes, I think so. I don't think we should be editing tags after they've been released and the current version of the plugin has the correct version number.

**Comment by sboisvert** [comment]
sounds good!
